In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('Gold Price.csv')

In [5]:
df

            Date   Price    Open    High     Low  Volume  Chg%
0     31-12-2025  135454  136526  136527  134866   59050  1.10
1     30-12-2025  133974  133185  134880  132853   36733  1.04
2     29-12-2025  132595  137628  138269  131695   90640 -3.77
3     26-12-2025  137789  136300  138300  136300   46771  1.24
4     24-12-2025  136104  136309  136500  135281   38763  0.22
...          ...     ...     ...     ...     ...     ...   ...
1540  07-01-2020   40635   40280   40666   40181   27470  0.46
1541  06-01-2020   40448   40250   41049   40250   33170  1.31
1542  03-01-2020   39925   39520   40002   39486     210  1.80
1543  02-01-2020   39220   38953   39685   38905     250  0.72
1544  01-01-2020   38938   38980   39067   38900     120 -0.16

[1545 rows x 7 columns]

In [8]:
df['Date'] = pd.to_datetime(df['Date'],format= '%d-%m-%Y')

In [9]:
df.head(25)

         Date   Price    Open    High     Low  Volume  Chg%
0  2025-12-31  135454  136526  136527  134866   59050  1.10
1  2025-12-30  133974  133185  134880  132853   36733  1.04
2  2025-12-29  132595  137628  138269  131695   90640 -3.77
3  2025-12-26  137789  136300  138300  136300   46771  1.24
4  2025-12-24  136104  136309  136500  135281   38763  0.22
5  2025-12-23  135799  134900  136888  134698   54815  0.86
6  2025-12-22  134638  132600  134688  132600   52738  1.67
7  2025-12-19  132427  132252  132575  131803   41184 -0.19
8  2025-12-18  132684  133117  133629  132090   50581 -0.32
9  2025-12-17  133115  132600  133490  132060   54875  0.37
10 2025-12-16  132627  132350  133399  131663   51610  0.10
11 2025-12-15  132491  131500  133633  131500   59083  0.64
12 2025-12-12  131645  130905  133282  130400   98046  0.57
13 2025-12-11  130905  128999  130988  128795   55011  1.87
14 2025-12-10  128500  129160  129163  128259   26343 -0.27
15 2025-12-09  128853  128893  129200  127833   41833  0.09
16 2025-12-08  128736  128900  129542  128301   34061 -0.36
17 2025-12-05  129206  128785  130200  128513   51597  0.24
18 2025-12-04  128894  129251  129389  128224   43318 -0.32
19 2025-12-03  129305  128999  130155  128999   55815  0.50
20 2025-12-02  128666  129325  129600  127912   60448  0.49
21 2025-12-01  128034  127279  128943  127279   25841  0.86
22 2025-11-28  126943  125899  127099  125625   50902  1.18
23 2025-11-27  125465  125360  125719  125087   26081 -0.17
24 2025-11-26  125674  125302  125800  124961   44486  0.61

In [10]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month_name()

In [11]:
monthly_avg = df.groupby(['Year', 'Month'])['Price'].mean().reset_index()

In [14]:
monthly_avg.head(20)

    Year      Month         Price
0   2020      April  45673.000000
1   2020     August  52946.380952
2   2020   December  49586.000000
3   2020   February  41237.619048
4   2020    January  40015.347826
5   2020       July  49998.347826
6   2020       June  47357.681818
7   2020      March  42290.454545
8   2020        May  46328.952381
9   2020   November  50203.863636
10  2020    October  50684.761905
11  2020  September  50904.772727
12  2021      April  46591.952381
13  2021     August  47101.909091
14  2021   December  47902.304348
15  2021   February  46955.600000
16  2021    January  49550.850000
17  2021       July  47758.227273
18  2021       June  47809.000000
19  2021      March  44687.260870

In [15]:
df['Month_Num'] = df['Date'].dt.month
monthly_avg = df.groupby(['Year', 'Month_Num', 'Month'])['Price'].mean().reset_index()
monthly_avg = monthly_avg.sort_values(['Year', 'Month_Num'])
monthly_avg = monthly_avg[['Year', 'Month', 'Price']]

In [18]:
monthly_avg.head(12)

    Year      Month         Price
0   2020    January  40015.347826
1   2020   February  41237.619048
2   2020      March  42290.454545
3   2020      April  45673.000000
4   2020        May  46328.952381
5   2020       June  47357.681818
6   2020       July  49998.347826
7   2020     August  52946.380952
8   2020  September  50904.772727
9   2020    October  50684.761905
10  2020   November  50203.863636
11  2020   December  49586.000000

In [19]:
monthly_avg.to_csv('Monthly_Gold_Price_2020_2025.csv', index=False)

In [20]:
monthly_avg

    Year      Month          Price
0   2020    January   40015.347826
1   2020   February   41237.619048
2   2020      March   42290.454545
3   2020      April   45673.000000
4   2020        May   46328.952381
..   ...        ...            ...
67  2025     August  100160.200000
68  2025  September  110007.500000
69  2025    October  122352.909091
70  2025   November  123449.200000
71  2025   December  131929.136364

[72 rows x 3 columns]